"""initial

Revision ID: e757c37d5e5b
Revises: 
Create Date: 2024-10-31 08:53:13.609426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e757c37d5e5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buses_in_company')
    op.drop_table('tickets')
    op.drop_table('company')
    op.drop_table('stops_and_routes')
    op.drop_table('review_passenger')
    op.drop_table('passengers')
    op.drop_table('report_income_company')
    op.drop_table('stops')
    op.drop_table('type_repair')
    op.drop_table('route_sheet')
    op.drop_table('delays_voyage')
    op.drop_table('routes')
    op.drop_table('order_repair')
    op.drop_table('drivers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('number_vy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('number_vy', name='drivers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('order_repair',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('buses_gos_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('detail_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buses_gos_number'], ['buses.gos_number'], name='order_repair_buses_gos_number_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detail_name'], ['type_repair.detail'], name='order_repair_detail_name_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='order_repair_pkey')
    )
    op.create_table('routes',
    sa.Column('number_route', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('count_stops', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_stop', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('end_stop', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('cost_travel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['end_stop'], ['stops.name'], name='routes_end_stop_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_stop'], ['stops.name'], name='routes_start_stop_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('number_route', name='routes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('delays_voyage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number_vy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cause', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('duration', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['number_vy'], ['drivers.number_vy'], name='delays_voyage_number_vy_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='delays_voyage_pkey')
    )
    op.create_table('route_sheet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number_vy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_route', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gos_number_bus', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gos_number_bus'], ['buses.gos_number'], name='route_sheet_gos_number_bus_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['number_route'], ['routes.number_route'], name='route_sheet_number_route_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['number_vy'], ['drivers.number_vy'], name='route_sheet_number_vy_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='route_sheet_pkey')
    )
    op.create_table('type_repair',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detail', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cost_detail', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='type_repair_pkey'),
    sa.UniqueConstraint('detail', name='unique_detail')
    )
    op.create_table('stops',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stops_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stops_pkey'),
    sa.UniqueConstraint('name', name='stops_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('report_income_company',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expenses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_name'], ['company.name'], name='report_income_company_company_name_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='report_income_company_pkey')
    )
    op.create_table('passengers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('passengers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='passengers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('review_passenger',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_passenger', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gos_number_bus', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_review', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gos_number_bus'], ['buses.gos_number'], name='review_passenger_gos_number_bus_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_passenger'], ['passengers.id'], name='review_passenger_id_passenger_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='review_passenger_pkey')
    )
    op.create_table('stops_and_routes',
    sa.Column('id_stops', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_route', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_stops'], ['stops.id'], name='stops_and_routes_id_stops_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['number_route'], ['routes.number_route'], name='stops_and_routes_number_route_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_stops', 'number_route', name='stops_and_routes_pkey')
    )
    op.create_table('company',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration_work', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('addres', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('number_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='company_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_passenger', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_travel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_stop', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('end_stop', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['end_stop'], ['stops.name'], name='tickets_end_stop_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_passenger'], ['passengers.id'], name='tickets_id_passenger_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_stop'], ['stops.name'], name='tickets_start_stop_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tickets_pkey')
    )
    op.create_table('buses_in_company',
    sa.Column('buses_gos_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buses_gos_number'], ['buses.gos_number'], name='buses_in_company_buses_gos_number_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_name'], ['company.name'], name='buses_in_company_company_name_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('buses_gos_number', 'company_name', name='buses_in_company_pkey')
    )
    # ### end Alembic commands ###
